Hent pakker ind

In [2]:
#installer pandas
pip install pandas
#installer statsmodels
pip install statsmodels
#installer matplotlib
pip install matplotlib
#installer pandas_datareader for famafrench data
pip install pandas_datareader

SyntaxError: invalid syntax (2321850156.py, line 2)

In [4]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import pandas_datareader.famafrench as ff_data
from pandas_datareader import data as web
import os

# Hent data ind

In [6]:
#os.chdir("/Users/emiliebrusch/Documents/Speciale/Kode")
ESG_data = pd.read_csv('ESG_P_MV_18Y.csv', sep = ';', decimal = ",")

ff_factor3_data = ff_data.FamaFrenchReader('F-F_Research_Data_Factors', start = pd.Timestamp('2004-06'),
                                                       end = pd.Timestamp('2021-11')).read()[0]

ff_factor4_data = ff_data.FamaFrenchReader('F-F_Momentum_Factor', start = pd.Timestamp('2004-06'),
                                                       end = pd.Timestamp('2021-11')).read()[0]

ff_factor5_data = ff_data.FamaFrenchReader('F-F_Research_Data_5_Factors_2x3', start = pd.Timestamp('2004-06'),
                                                              end = pd.Timestamp('2021-11')).read()[0]


ff_factor3_data = ff_factor3_data.apply(lambda x: x/100, axis=1)
ff_factor4_data = ff_factor4_data.apply(lambda x: x/100, axis=1)
ff_factor5_data = ff_factor5_data.apply(lambda x: x/100, axis=1)

In [8]:
col = ESG_data.columns[:-1]
ESG_data = ESG_data.drop('01.04.2004',1)
ESG_data.columns = col
ESG_data

/var/folders/vh/3c0__ql90lvf1cs2fv9z99_w0000gn/T/ipykernel_67191/2204911993.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  ESG_data = ESG_data.drop('01.04.2004',1)

,Name,01.04.2004,01.05.2004,01.06.2004,01.07.2004,01.08.2004,01.09.2004,01.10.2004,01.11.2004,01.12.2004,...,01.02.2021,01.03.2021,01.04.2021,01.05.2021,01.06.2021,01.07.2021,01.08.2021,01.09.2021,01.10.2021,01.11.2021
0,A-MARK PRECIOUS METALS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.80,35.38,38.71,54.49,46.80,50.25,48.96,62.92,74.70,66.66
1,A-MARK PRECIOUS METALS - MARKET VALUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,214.42,340.76,372.83,606.81,521.18,559.60,545.23,710.44,848.00,756.73
2,A-MARK PRECIOUS METALS - Environment Pillar Score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.84,16.84,16.84,16.84,NaN,NaN,NaN,NaN,NaN,NaN
3,A-MARK PRECIOUS METALS - Social Pillar Score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.39,19.39,19.39,19.39,NaN,NaN,NaN,NaN,NaN,NaN
4,A-MARK PRECIOUS METALS - Governance Pillar Score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,47.78,47.78,47.78,47.78,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21379,908 DEVICES - MARKET VALUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1505.76,1422.49,1428.62,1213.49,1013.11,865.69,998.13,967.17,992.96,669.60
21380,908 DEVICES - Environment Pillar Score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21381,908 DEVICES - Social Pillar Score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21382,908 DEVICES - Governance Pillar Score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21383,908 DEVICES - ESG Score,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
esg_idx = ESG_data['Name'].str.split('-').str[-1].str.strip(' ') == 'ESG Score'
full_esg = ESG_data[esg_idx]
print('Mean ESG score', np.nanmean(full_esg[full_esg.columns[1:]].astype('float64').values))
print('STD ESG score', np.nanstd(full_esg[full_esg.columns[1:]].astype('float64').values))
print('Min. ESG score', np.nanmin(full_esg[full_esg.columns[1:]].astype('float64').values))
print('Max. ESG score', np.nanmax(full_esg[full_esg.columns[1:]].astype('float64').values))

Mean ESG score 38.49792565968768
STD ESG score 19.064831389480428
Min. ESG score 0.34
Max. ESG score 95.15

# Fordel porteføljer

In [10]:
# extract the data from june every year
june_data = ESG_data[ESG_data.columns[3::12]]
june_data['Name'] = ESG_data['Name']
june_data = june_data[['Name',*ESG_data.columns[3::12]]]

/var/folders/vh/3c0__ql90lvf1cs2fv9z99_w0000gn/T/ipykernel_67191/586992501.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  june_data['Name'] = ESG_data['Name']

In [11]:
# get esg scores from each company
esg_idx = june_data['Name'].str.split('-').str[-1].str.strip(' ') == 'ESG Score'
esg_june_data = june_data[esg_idx]
esg_june_data

# get MV scores from each company
esg_mv_idx = june_data['Name'].str.split('-').str[-1].str.strip(' ') == 'MARKET VALUE'
mv_june_data = june_data[esg_mv_idx]
assert(len(esg_june_data) == len(mv_june_data))

In [13]:
# get list of companies in each portfolio each year
# at each key in all of these portfolios, there should exist a new dictionary.
# keys are decile numbers
companies = dict()
esg = dict()
meanesg = dict()

# loop through all year in the dataset
for year in esg_june_data.columns[1:]:
    # get all companies for which the ESG Scores are not NaN
    company_names = esg_june_data['Name'][esg_june_data[year].notnull()].str[:-12]
    
    # divide into 10 partitions based on ESG Scores
    deciles = pd.qcut(esg_june_data[year][esg_june_data[year].notnull()], 10, labels=False)
    
    # Loop through every decile and assign each decile to the companies dictionary
    for dec in range(10):
        dec_idx = deciles == dec
        dec_names = company_names[dec_idx]
        
        # make sure the dictionarys exist at each decile key - and use 1 indexing for good measure.
        if dec+1 not in companies.keys():
            companies[dec+1] = dict()
            esg[dec+1] = np.array([])
            meanesg[dec+1] = dict()
            
        # fill decile keys with data
        esg[dec+1] = np.append(esg[dec+1], esg_june_data[year][esg_june_data[year].notnull()][dec_idx].values)
        meanesg[dec+1][year] = np.mean(esg_june_data[year][esg_june_data[year].notnull()][dec_idx].values)

        companies[dec+1][year] = dec_names

# Oversigt over porteføljer
Ændre tal og årstal for at se antal virksomheder osv. i hvert portefølge for hvert år

In [14]:
# ESG & MV
# 
stats_dict_esg = dict()
stats_dict_mv = dict()
for k in companies:
    stats_dict_mv[k] = dict()
    stats_dict_esg[k] = dict()
        
for i in companies:
    for year in companies[i]:
        
        names = companies[i][year] + " - MARKET VALUE"
        stats_dict_mv[i][year] = ESG_data.loc[ESG_data["Name"].isin(list(names))][year].sum()
        
        names = companies[i][year] + " - ESG Score"
        stats_dict_esg[i][year] = ESG_data.loc[ESG_data["Name"].isin(list(names))][year].mean()

In [15]:
# ændrer tal for at ændre portefølje. Ændre årstal
portfolio = 10
year = '2020'
print('Antal virksomheder:\n', len(companies[portfolio]['01.06.' + year]))
print('\nVirksomheder:\n', companies[portfolio]['01.06.' + year].values)
print('\nMiddel ESG for portefølje i givne år:',meanesg[portfolio]['01.06.' + year])
print('\nMiddel ESG for portefølje på tværs af år:', np.mean(esg[portfolio]))
print('\nMiddel MV for portefølje på tværs af år:',np.mean(list(stats_dict_mv[portfolio].values())))
print('\nSum MV for portefølje på tværs af år:', np.sum(list(stats_dict_mv[portfolio].values())))

Antal virksomheder:
 337

Virksomheder:
 ['ABBOTT LABORATORIES' 'ABBVIE' 'ABM INDS.'
 'ACADIA REAL.TST.SHRE. BEN INT' 'ACCENTURE CLASS A' 'ACCO BRANDS'
 'ADOBE (NAS)' 'ADTALEM GLOBAL EDUCATION' 'AES' 'AGILENT TECHS.'
 'AGNICO-EAGLE MNS. (NYS)' 'AIR PRDS.& CHEMS.' 'ALBEMARLE' 'ALCOA'
 'ALEXANDRIA RLST.EQTIES.' 'ALLEGION' 'BREAD FINANCIAL HOLDINGS'
 'ALLSTATE ORD SHS' 'ALTRIA GROUP' 'AMAZON.COM' 'AMCOR' 'AMDOCS'
 'AMER.AXLE & MNFG.' 'AMER.ELEC.PWR.' 'AMERICAN EXPRESS' 'AMERICAN TOWER'
 'AMERICAN WATER WORKS' 'AMERICOLD REALTY TRUST' 'AMERIPRISE FINL.'
 'AMERISOURCEBERGEN' 'AMGEN' 'AMN HLTHCR.SVS.' "AMPHENOL 'A'"
 'ANALOG DEVICES' 'ANTHEM' 'APPLE' 'APPLIED MATS.'
 'ARCHER DANIELS MIDLAND' 'ARCONIC' 'ARGO GP.INTL.HOLDINGS' 'AT&T'
 'AUTODESK' 'AUTOZONE' 'AVALONBAY COMMNS.' 'AVANGRID' 'AVIENT'
 'BAKER HUGHES A' 'BALL' 'BANK OF AMERICA' 'BANK OF NEW YORK MELLON'
 'BARRICK GOLD (NYS)' 'BAUSCH HEALTH (NYS) COMPANIES' 'BAXTER INTL.'
 'BECTON DICKINSON' 'BEIGENE ADS 1:13' 'BERRY GLOBAL GROUP' 'BEST BUY'
 'BIOGEN' 'BIONTECH SE ADR 1:1' 'BLACKBERRY (NYS)' 'BOEING'
 'BOSTON PROPERTIES' 'BOSTON SCIENTIFIC' 'BRANDYWINE REAL.TST.SHBI NEW'
 'BRISTOL MYERS SQUIBB' 'BROADRIDGE FINL.SLTN.' 'BROOKDALE SENIOR LIVING'
 "BROOKFIELD ASSET MAN.'A' (NYS)" 'BRUNSWICK' 'BUNGE' 'CABOT'
 'CADENCE DESIGN SYS.' 'CALERES' 'CAMPBELL SOUP' 'CARLISLE COS.'
 'CARNIVAL' "CARTER'S" 'CATERPILLAR' 'CBRE GROUP CLASS A' 'CDW'
 'CENTERSPACE' 'CF INDUSTRIES HDG.' 'CHEESECAKE FACTORY' 'CHENIERE EN.'
 'CHEVRON' 'CHINA JO JO DRUGSTORES' 'CHURCH & DWIGHT CO.' 'CIGNA' 'CINTAS'
 'CISCO SYSTEMS' 'CITIGROUP' 'CNO FINANCIAL GROUP' 'COCA COLA'
 'COCA COLA EUROPACIFIC PARTNERS' 'COEUR MINING' 'COLGATE-PALM.'
 'COMCAST A' 'COMERICA' 'CONOCOPHILLIPS' 'COSTCO WHOLESALE'
 'CRITEO ADR 1:1' 'CROSS COUNTRY HLTHCR.' 'CROWN CASTLE INTL.'
 'CUSHMAN AND WAKEFIELD' 'CVS HEALTH' 'DANAHER' 'DEERE'
 'DIGITAL REALTY TST.' 'DOMINION ENERGY' 'DOW ORD SHS' 'DTE ENERGY'
 'DUKE ENERGY' 'EASTMAN CHEMICAL' 'EATON' 'ECOLAB' 'EDISON INTL.'
 'ELI LILLY' 'EMERSON ELECTRIC' 'ENPRO INDS.' 'EPAM SYSTEMS'
 'EQUINIX REIT' 'EQUITRANS MIDSTREAM' 'ESSEX PROPERTY TST.'
 'EVERSOURCE ENERGY' 'FEDERAL REALTY INV.TST.' 'FIFTH THIRD BANCORP'
 'FIRST SOLAR' 'FIRSTENERGY' 'FLEX' 'FLOWSERVE' 'FMC' 'FORD MOTOR' 'FOX A'
 'FREEPORT-MCMORAN' 'FRESH DEL MONTE PRODUCE' 'FTI CONSULTING' 'F5'
 'GENERAL ELECTRIC' 'GENERAL MOTORS' 'GENPACT' 'GOLDMAN SACHS GP.'
 'HAIN CELESTIAL GP.' 'HALLIBURTON' 'HANNON ARMS.SUST.INFR. CAP.'
 'HARTFORD FINL.SVS.GP.' 'HASBRO' 'HEALTHPEAK PROPERTIES' 'HECLA MINING'
 'HELEN OF TROY' 'HENRY SCHEIN' 'HERC HOLDINGS' 'HERSHEY' 'HESS'
 'HEWLETT PACKARD ENTER.' 'HILTON WORLDWIDE HDG.' 'HOLOGIC' 'HOME DEPOT'
 'HONEYWELL INTL.' 'HORACE MANN EDUCATORS' 'HORMEL FOODS'
 'HOST HOTELS & RESORTS REIT' 'HP' 'HUDSON PACIFIC PROPS.'
 'HUNTINGTON BCSH.' 'HUNTSMAN' 'ILLUMINA' 'INCYTE' 'INSULET' 'INTEL'
 'INTERNATIONAL BUS.MCHS.' 'INTERNATIONAL GAME TECH.'
 'INTL.FLAVORS & FRAG.' 'INTUIT' 'INVESCO' 'IPG PHOTONICS' 'ITRON' 'ITT'
 'JACOBS ENGR.' 'JBG SMITH PROPERTIES' 'JD COM ADR 1:2'
 'JOHNSON & JOHNSON' 'JOHNSON CONTROLS INTL.' 'JONES LANG LASALLE'
 'JP MORGAN CHASE & CO.' 'JUNIPER NETWORKS' 'KB HOME' 'KBR'
 "KELLY SERVICES 'A'" 'KEYSIGHT TECHNOLOGIES' 'KILROY REALTY'
 'KIMBERLY-CLARK' 'KIMCO REALTY' 'KINDER MORGAN' 'KINROSS GOLD (NYS)'
 "KOHL'S" 'KROGER' 'LABORATORY CORP.OF AM. HDG.' 'LEAR' 'LEIDOS HOLDINGS'
 'LINDE' 'LOCKHEED MARTIN' "LOWE'S COMPANIES" 'LPL FINANCIAL HOLDINGS'
 'LUMENTUM HOLDINGS' 'MACERICH' 'MARATHON OIL' 'MARATHON PETROLEUM'
 "MARRIOTT INTL.'A'" 'MASCO' 'MASTERCARD' 'MCCORMICK & COMPANY NV.'
 'MCDONALDS' 'MELCO RESORTS ENTERTAINMENT ADR 1:3' 'MERCK & COMPANY'
 'MERIT MEDICAL SYS.' 'MICRON TECHNOLOGY' 'MID-AMER.APT COMMUNITIES'
 'MILLICOM INTL.CELU.' 'MONDELEZ INTERNATIONAL CL.A' "MOODY'S" 'MOSAIC'
 'MOTOROLA SOLUTIONS' 'MSA SAFETY' 'NABORS INDUSTRIES' 'NASDAQ'
 'NETEASE ADR 1:5' 'NEWELL BRANDS (XSC)' 'NEWMONT' 'NEXA RESOURCES'
 'NEXTERA ENERGY' "NOAH HOLDINGS 'A' 2:1 ADR" 'NORDSTROM'
 'NORTHROP GRUMMAN' 'NORTHWESTERN' 'NORTONLIFELOCK' 'NRG ENERGY' 'NVIDIA'
 'NXP SEMICONDUCTORS' 'OMNICOM GROUP' 'ON SEMICONDUCTOR' 'ONEOK'
 'OPEN TEXT (NAS)' 'OSHKOSH' 'OWENS CORNING' 'PACKAGING CORP.OF AM.'
 'PAN AMERICAN SILVER(NAS)' 'PARAMOUNT GLOBAL B' 'PAYPAL HOLDINGS'
 'PEBBLEBROOK HOTEL TRUST' 'PEPSICO' 'PERKINELMER' 'PFIZER' 'PG&E'
 'PHILIP MORRIS INTL.' 'PHILLIPS 66' "PIEDMONT OFFE.REAL.TST. 'A'"
 'PNC FINL.SVS.GP.' 'POLARIS INDUSTRIES' 'POTLATCHDELTIC' 'PPG INDUSTRIES'
 'PROLOGIS REIT' 'PRUDENTIAL FINL.' 'PUBLIC STORAGE' 'PVH' 'QIAGEN'
 'QUEST DIAGNOSTICS' 'REALTY INCOME' 'REGENCY CENTERS' "REPUBLIC SVS.'A'"
 'RESIDEO TECHNOLOGIES' 'RESMED' 'ROBERT HALF INTL.' 'ROGERS'
 'ROYAL CARIBBEAN GROUP' 'RYDER SYSTEM' 'SCHLUMBERGER'
 'SCIENCE APPS.INTL.' 'SEMPRA' 'SHERWIN-WILLIAMS' 'SIGNET JEWELERS'
 'SIMPSON MNFG.' 'SITE CENTERS (NYS)' 'SOLAREDGE TECHNOLOGIES' 'SOUTHERN'
 'SOUTHWEST AIRLINES' 'SPIRIT AEROSYSTEMS CL.A' 'STANLEY BLACK & DECKER'
 'STARBUCKS' 'STATE STREET' "STEELCASE 'A'" 'STERICYCLE' 'STRYKER'
 'SUNSTONE HTL.INVRS.' 'SYNOPSYS' 'TARGET' 'TE CONNECTIVITY' 'TETRA TECH'
 'TEXAS INSTRUMENTS' 'TEXTRON' 'THERMO FISHER SCIENTIFIC' 'TJX'
 'TRACTOR SUPPLY' 'TRANE TECHNOLOGIES' 'UBER TECHNOLOGIES' 'UNION PACIFIC'
 "UNITED PARCEL SER.'B'" 'UNITED RENTALS' 'UNITEDHEALTH GROUP'
 'VALERO ENERGY' 'VALVOLINE' 'VENTAS' 'VERISK ANALYTICS CL.A'
 'VERIZON COMMUNICATIONS' 'VIATRIS' 'VIPSHOP HOLDINGS SPONSORED ADS 5:1'
 'VISTA OUTDOOR' 'WALGREENS BOOTS ALLIANCE' 'WALT DISNEY'
 'WASTE MANAGEMENT' 'WATERS' 'WAVE LIFE SCIENCES' 'WELLS FARGO & CO'
 "WENDY'S CLASS A" 'WEST PHARM.SVS.' 'WESTROCK' 'WEYERHAEUSER' 'WHIRLPOOL'
 'WILLIAMS' 'WILLIAMS-SONOMA' 'WOLFSPEED' 'WW GRAINGER' 'WYNN RESORTS'
 'XCEL ENERGY' 'XYLEM' 'YUM CHINA HOLDINGS' 'YUM! BRANDS' '3M']

Middel ESG for portefølje i givne år: 75.51563798219584

Middel ESG for portefølje på tværs af år: 75.41317229585292

Middel MV for portefølje på tværs af år: 6982704.411666665

Sum MV for portefølje på tværs af år: 125688679.40999998

# Regn afkast for alle virksomheder

In [16]:
# afkast
afkast = ESG_data.iloc[0::6]
afkast.index = afkast['Name']
afkast = afkast.drop(columns='Name')
afkast = afkast.T
afkast = afkast.astype('float64')

# market value
MV = ESG_data.iloc[1::6]
MV.index = MV['Name']
MV = MV.drop(columns='Name')
MV = MV.T
MV = MV.astype('float64')

#use columns names from afkast
MV.columns = afkast.columns

In [17]:
afkast_diff = afkast.pct_change(1)

# Construct portfolios

In [18]:
portfolio = pd.DataFrame()
VALUE_WEIGHTED = True

for dec in companies.keys():
    dec_temp = pd.DataFrame()
    for year in companies[dec].keys():
        portfolio_dec_year = companies[dec][year]
        start_idx = np.where(afkast_diff.index == year)[0][0]
        
        # afkast
        period_afkast = afkast_diff[start_idx:start_idx+12][portfolio_dec_year]
        
        if VALUE_WEIGHTED:
            #weights
            period_MV = MV[start_idx:start_idx+12][portfolio_dec_year]
            period_MV = period_MV.apply(lambda row: row[list(period_MV.columns)]/row.sum(), axis=1)
        
            # weighted returns based on MV
            period_afkast = period_afkast.multiply(period_MV, axis=1)
            
            # take the mean on the weighted returns
            data = period_afkast.sum(axis=1)
        else:
            data = period_afkast.mean(axis=1)
        

        temp = pd.DataFrame({dec: data}, index = afkast_diff.index[start_idx:start_idx+12])
        dec_temp = pd.concat((dec_temp, temp), axis = 0)
        
    portfolio[dec] = dec_temp

In [19]:
portfolio['GMB'] = portfolio[10] - portfolio[1]
portfolio

,1,2,3,4,5,6,7,8,9,10,GMB
01.06.2004,0.008887,0.031444,0.028727,0.027749,0.024988,-0.008109,0.014550,-0.011664,0.004930,0.013294,0.004407
01.07.2004,0.001457,-0.005392,-0.020355,-0.006096,-0.025500,-0.001585,-0.000980,-0.043132,-0.019232,-0.017044,-0.018501
01.08.2004,0.005121,0.015539,-0.014216,0.018691,0.017453,0.006419,0.010442,0.000812,0.006465,-0.016904,-0.022025
01.09.2004,0.025142,0.019469,0.049383,0.035859,0.046509,0.046976,0.023055,0.002329,0.023892,0.019387,-0.005754
01.10.2004,-0.005618,0.021018,0.017655,0.009049,0.015164,0.032027,-0.015781,-0.022871,0.017473,0.006774,0.012391
...,...,...,...,...,...,...,...,...,...,...,...
01.07.2021,-0.021054,0.016991,0.012144,-0.086989,0.046446,0.028164,-0.001879,-0.052015,0.023268,0.050096,0.071150
01.08.2021,-0.037152,-0.019281,-0.024986,0.051504,0.110502,0.021223,0.041661,-0.019156,0.091079,0.060360,0.097512
01.09.2021,0.016529,-0.038144,-0.018947,-0.018868,-0.062475,-0.056200,-0.016653,0.030361,0.035307,-0.042616,-0.059145
01.10.2021,0.136072,0.045609,-0.034573,0.025456,0.168811,0.091328,0.079704,-0.001993,0.054396,0.060893,-0.075179
01.11.2021,-0.088633,-0.059785,-0.088342,-0.091044,-0.023488,-0.047837,-0.042388,-0.077363,-0.002932,0.035533,0.124167

In [ ]:
#skriv til csv
#portfolio.to_csv('returns_portfolios_VW.csv')

In [20]:
portfolio_merafkast = portfolio.sub(pd.Series(list(ff_factor3_data['RF']), index=portfolio.index), axis='index')

In [21]:
def linreg(Y,X):
    X = sm.add_constant(X, prepend=True)
    mod = sm.OLS(Y,X)
    res = mod.fit()
    return res

In [22]:
### CAPM
portfolio_navn = "GMB" # 1..10 + "GMB"

CAPM_X = np.array(list(ff_factor3_data['Mkt-RF']))
CAPM_Y = np.array(list(portfolio_merafkast[portfolio_navn]))

print(CAPM_Y.shape)
res = linreg(CAPM_Y, CAPM_X)

print(res.summary())

(210,)
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.126
Model:                            OLS   Adj. R-squared:                  0.122
Method:                 Least Squares   F-statistic:                     30.09
Date:                Thu, 14 Apr 2022   Prob (F-statistic):           1.19e-07
Time:                        10:00:47   Log-Likelihood:                 391.96
No. Observations:                 210   AIC:                            -779.9
Df Residuals:                     208   BIC:                            -773.2
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0085      0.003     -3.208      0.002      -0.014      -0.003
x1            -0.3302      0.060     -5.485      0.000      -0.449      -0.212
==============================================================================
Omnibus:                       27.736   Durbin-Watson:                   1.763
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               92.840
Skew:                          -0.452   Prob(JB):                     6.92e-21
Kurtosis:                       6.129   Cond. No.                         23.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [23]:
### fama french 3 factor model
portfolio_navn = "GMB"

FF3_X = np.array((list(ff_factor3_data['Mkt-RF']), 
                  list(ff_factor3_data['SMB']),
                  list(ff_factor3_data['HML']))).T

FF3_Y = np.array(list(portfolio_merafkast[portfolio_navn]))

res = linreg(FF3_Y, FF3_X)
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.285
Model:                            OLS   Adj. R-squared:                  0.275
Method:                 Least Squares   F-statistic:                     27.43
Date:                Thu, 14 Apr 2022   Prob (F-statistic):           5.76e-15
Time:                        10:00:50   Log-Likelihood:                 413.06
No. Observations:                 210   AIC:                            -818.1
Df Residuals:                     206   BIC:                            -804.7
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0088      0.002     -3.627      0.000      -0.014      -0.004
x1            -0.2044      0.060     -3.414      0.001      -0.322      -0.086
x2            -0.7116      0.106     -6.711      0.000      -0.921      -0.503
x3             0.1194      0.084      1.422      0.156      -0.046       0.285
==============================================================================
Omnibus:                       15.537   Durbin-Watson:                   1.929
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               35.782
Skew:                          -0.275   Prob(JB):                     1.70e-08
Kurtosis:                       4.946   Cond. No.                         46.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [36]:
### fama french 4 factor model
portfolio_navn = 'GMB'

FF4_X = np.array((list(ff_factor3_data['Mkt-RF']), 
                  list(ff_factor3_data['SMB']),
                  list(ff_factor3_data['HML']),
                  list(ff_factor4_data['Mom   ']))).T

FF4_Y = np.array(list(portfolio_merafkast[portfolio_navn]))

res = linreg(FF4_Y, FF4_X)
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.344
Model:                            OLS   Adj. R-squared:                  0.331
Method:                 Least Squares   F-statistic:                     26.91
Date:                Thu, 14 Apr 2022   Prob (F-statistic):           5.94e-18
Time:                        17:22:55   Log-Likelihood:                 422.09
No. Observations:                 210   AIC:                            -834.2
Df Residuals:                     205   BIC:                            -817.4
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0094      0.002     -4.053      0.000      -0.014      -0.005
x1            -0.1311      0.060     -2.187      0.030      -0.249      -0.013
x2            -0.7122      0.102     -6.995      0.000      -0.913      -0.511
x3             0.2669      0.088      3.046      0.003       0.094       0.440
x4             0.2560      0.060      4.289      0.000       0.138       0.374
==============================================================================
Omnibus:                       14.926   Durbin-Watson:                   1.906
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               40.948
Skew:                          -0.138   Prob(JB):                     1.28e-09
Kurtosis:                       5.146   Cond. No.                         46.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [25]:
### fama french 5 factor model
portfolio_navn = "GMB"

FF5_X = np.array((list(ff_factor5_data['Mkt-RF']), 
                  list(ff_factor5_data['SMB']),
                  list(ff_factor5_data['HML']),
                  list(ff_factor5_data['RMW']),
                  list(ff_factor5_data['CMA']))).T

FF5_Y = np.array(list(portfolio_merafkast[portfolio_navn]))

res = linreg(FF5_Y, FF5_X)
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.370
Model:                            OLS   Adj. R-squared:                  0.355
Method:                 Least Squares   F-statistic:                     23.99
Date:                Thu, 14 Apr 2022   Prob (F-statistic):           5.98e-19
Time:                        10:00:55   Log-Likelihood:                 426.33
No. Observations:                 210   AIC:                            -840.7
Df Residuals:                     204   BIC:                            -820.6
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0111      0.002     -4.735      0.000      -0.016      -0.006
x1            -0.1201      0.059     -2.038      0.043      -0.236      -0.004
x2            -0.6087      0.105     -5.787      0.000      -0.816      -0.401
x3             0.0511      0.095      0.540      0.589      -0.135       0.237
x4             0.4987      0.138      3.603      0.000       0.226       0.772
x5             0.5880      0.173      3.403      0.001       0.247       0.929
==============================================================================
Omnibus:                       31.261   Durbin-Watson:                   1.946
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               77.569
Skew:                          -0.649   Prob(JB):                     1.43e-17
Kurtosis:                       5.680   Cond. No.                         81.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.